import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: corsHeaders });

  try {
    const GOOGLE_AI_API_KEY = Deno.env.get("GOOGLE_AI_API_KEY");
    if (!GOOGLE_AI_API_KEY) throw new Error("GOOGLE_AI_API_KEY is not configured");

    const SUPABASE_URL = Deno.env.get("SUPABASE_URL");
    const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
    if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) throw new Error("Supabase config missing");

    const { prompt, model, referenceImageBase64, sceneIndex, projectName } = await req.json();
    if (!prompt) throw new Error("prompt is required");

    // Use actual Imagen 4 API via Google AI Studio
    const imagenModel = model || "imagen-4.0-generate-001";
    const apiUrl = `https://generativelanguage.googleapis.com/v1beta/models/${imagenModel}:predict?key=${GOOGLE_AI_API_KEY}`;

    // Build Imagen 4 request
    const instances: any = { prompt };

    // If reference image provided, include as reference for structural continuity
    if (referenceImageBase64) {
      const cleanBase64 = referenceImageBase64.includes(",")
        ? referenceImageBase64.split(",")[1]
        : referenceImageBase64;
      instances.referenceImages = [{
        referenceImage: { bytesBase64Encoded: cleanBase64 },
        referenceType: "STYLE_IMAGE",
      }];
      console.log(`Using reference image for scene continuity via Imagen 4 style reference`);
    }

    // Scene-aware person generation policy per master prompt:
    // Scenes 2,3,5,6 (indices 1,2,4,5) REQUIRE workers → allow person generation
    // Scenes 4,7,8 (indices 3,6,7) workers OPTIONAL → allow person generation
    // Scenes 1,9 (indices 0,8) NO workers → block person generation
    const idx = sceneIndex ?? -1;
    const noWorkersScenes = [0, 8]; // atmosphere-only scenes
    const personGeneration = noWorkersScenes.includes(idx) ? "DONT_ALLOW" : "ALLOW_ADULT";

    console.log(`Scene ${idx + 1}: personGeneration=${personGeneration}`);

    const requestBody = {
      instances: [instances],
      parameters: {
        sampleCount: 1,
        aspectRatio: "9:16",
        personGeneration,
        safetyFilterLevel: "BLOCK_MEDIUM_AND_ABOVE",
      },
    };

    console.log(`Calling Imagen 4: model=${imagenModel}, prompt length=${prompt.length}, hasReference=${!!referenceImageBase64}`);

    const response = await fetch(apiUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(requestBody),
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error("Imagen 4 API error:", response.status, errorText);

      if (response.status === 429) {
        return new Response(JSON.stringify({
          error: "API quota exceeded. Wait a few minutes and try again.",
          errorCode: "RATE_LIMITED",
        }), {
          status: 429,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        });
      }

      return new Response(JSON.stringify({
        error: `Imagen 4 API error (${response.status})`,
        details: errorText.substring(0, 500),
      }), {
        status: response.status,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const data = await response.json();

    // Extract image from Imagen 4 response
    const prediction = data.predictions?.[0];
    if (!prediction?.bytesBase64Encoded) {
      console.error("No image in Imagen 4 response:", JSON.stringify(data).substring(0, 500));
      return new Response(JSON.stringify({
        error: "No image generated by Imagen 4",
        details: "The model did not return an image. Try simplifying the prompt.",
        raw: JSON.stringify(data).substring(0, 1000),
      }), {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const imageBase64 = prediction.bytesBase64Encoded;

    // Upload to Cloud storage
    const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);
    const safeName = (projectName || "project").replace(/[^a-zA-Z0-9_-]/g, "_");
    const fileName = `${safeName}/scenes/scene_${(sceneIndex ?? 0) + 1}_${Date.now()}.png`;
    const imageBytes = Uint8Array.from(atob(imageBase64), (c) => c.charCodeAt(0));

    const { error: uploadError } = await supabase.storage
      .from("bunker-assets")
      .upload(fileName, imageBytes, { contentType: "image/png", upsert: true });

    if (uploadError) {
      console.error("Storage upload error:", uploadError);
      return new Response(JSON.stringify({
        imageUrl: `data:image/png;base64,${imageBase64}`,
        imageBase64,
        storageError: uploadError.message,
      }), {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const { data: publicUrl } = supabase.storage
      .from("bunker-assets")
      .getPublicUrl(fileName);

    return new Response(JSON.stringify({
      imageUrl: publicUrl.publicUrl,
      imageBase64,
      storagePath: fileName,
    }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (e) {
    console.error("imagen-generate error:", e);
    return new Response(JSON.stringify({ error: e instanceof Error ? e.message : "Unknown error" }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
